// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { SmartAccountFactory$Type } from "./SmartAccountFactory";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SmartAccountFactory"]: SmartAccountFactory$Type;
    ["contracts/proxy/SmartAccountFactory.sol:SmartAccountFactory"]: SmartAccountFactory$Type;
  }

  interface ContractTypesMap {
    ["SmartAccountFactory"]: GetContractReturnType<SmartAccountFactory$Type["abi"]>;
    ["contracts/proxy/SmartAccountFactory.sol:SmartAccountFactory"]: GetContractReturnType<SmartAccountFactory$Type["abi"]>;
  }
}
