// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { OptimisticOracleV3Interface$Type } from "./OptimisticOracleV3Interface";
import { Wagemore$Type } from "./Wagemore";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["OptimisticOracleV3Interface"]: OptimisticOracleV3Interface$Type;
    ["Wagemore"]: Wagemore$Type;
    ["contracts/Wagemore.sol:OptimisticOracleV3Interface"]: OptimisticOracleV3Interface$Type;
    ["contracts/Wagemore.sol:Wagemore"]: Wagemore$Type;
  }

  interface ContractTypesMap {
    ["OptimisticOracleV3Interface"]: GetContractReturnType<OptimisticOracleV3Interface$Type["abi"]>;
    ["Wagemore"]: GetContractReturnType<Wagemore$Type["abi"]>;
    ["contracts/Wagemore.sol:OptimisticOracleV3Interface"]: GetContractReturnType<OptimisticOracleV3Interface$Type["abi"]>;
    ["contracts/Wagemore.sol:Wagemore"]: GetContractReturnType<Wagemore$Type["abi"]>;
  }
}
