// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { OptimisticOracleV3Interface$Type } from "./OptimisticOracleV3Interface";
import { WagemoreWithOracle$Type } from "./WagemoreWithOracle";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["OptimisticOracleV3Interface"]: OptimisticOracleV3Interface$Type;
    ["WagemoreWithOracle"]: WagemoreWithOracle$Type;
    ["contracts/WagemoreWithOracle.sol:OptimisticOracleV3Interface"]: OptimisticOracleV3Interface$Type;
    ["contracts/WagemoreWithOracle.sol:WagemoreWithOracle"]: WagemoreWithOracle$Type;
  }

  interface ContractTypesMap {
    ["OptimisticOracleV3Interface"]: GetContractReturnType<OptimisticOracleV3Interface$Type["abi"]>;
    ["WagemoreWithOracle"]: GetContractReturnType<WagemoreWithOracle$Type["abi"]>;
    ["contracts/WagemoreWithOracle.sol:OptimisticOracleV3Interface"]: GetContractReturnType<OptimisticOracleV3Interface$Type["abi"]>;
    ["contracts/WagemoreWithOracle.sol:WagemoreWithOracle"]: GetContractReturnType<WagemoreWithOracle$Type["abi"]>;
  }
}
