/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as publicPublicRouteRouteImport } from './app/(public)/_public/route'
import { Route as publicauthRouteRouteImport } from './app/(public)/(auth)/route'
import { Route as publicMarketsIndexRouteImport } from './app/(public)/markets/index'
import { Route as publicPublicIndexRouteImport } from './app/(public)/_public/index'
import { Route as ApiAuthSplatRouteImport } from './app/api/auth/$'
import { Route as publicDashboardHomeIndexRouteImport } from './app/(public)/dashboard/home/index'
import { Route as publicauthOnboardingIndexRouteImport } from './app/(public)/(auth)/onboarding/index'
import { Route as publicauthLoginIndexRouteImport } from './app/(public)/(auth)/login/index'

const publicPublicRouteRoute = publicPublicRouteRouteImport.update({
  id: '/(public)/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const publicauthRouteRoute = publicauthRouteRouteImport.update({
  id: '/(public)/(auth)',
  path: '',
  getParentRoute: () => rootRouteImport,
} as any)
const publicMarketsIndexRoute = publicMarketsIndexRouteImport.update({
  id: '/(public)/markets/',
  path: '/markets/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicPublicIndexRoute = publicPublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicPublicRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const publicDashboardHomeIndexRoute =
  publicDashboardHomeIndexRouteImport.update({
    id: '/(public)/dashboard/home/',
    path: '/dashboard/home/',
    getParentRoute: () => rootRouteImport,
  } as any)
const publicauthOnboardingIndexRoute =
  publicauthOnboardingIndexRouteImport.update({
    id: '/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => publicauthRouteRoute,
  } as any)
const publicauthLoginIndexRoute = publicauthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => publicauthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/': typeof publicPublicIndexRoute
  '/markets': typeof publicMarketsIndexRoute
  '/login': typeof publicauthLoginIndexRoute
  '/onboarding': typeof publicauthOnboardingIndexRoute
  '/dashboard/home': typeof publicDashboardHomeIndexRoute
}
export interface FileRoutesByTo {
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/': typeof publicPublicIndexRoute
  '/markets': typeof publicMarketsIndexRoute
  '/login': typeof publicauthLoginIndexRoute
  '/onboarding': typeof publicauthOnboardingIndexRoute
  '/dashboard/home': typeof publicDashboardHomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)/(auth)': typeof publicauthRouteRouteWithChildren
  '/(public)/_public': typeof publicPublicRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(public)/_public/': typeof publicPublicIndexRoute
  '/(public)/markets/': typeof publicMarketsIndexRoute
  '/(public)/(auth)/login/': typeof publicauthLoginIndexRoute
  '/(public)/(auth)/onboarding/': typeof publicauthOnboardingIndexRoute
  '/(public)/dashboard/home/': typeof publicDashboardHomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/api/auth/$'
    | '/'
    | '/markets'
    | '/login'
    | '/onboarding'
    | '/dashboard/home'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/auth/$'
    | '/'
    | '/markets'
    | '/login'
    | '/onboarding'
    | '/dashboard/home'
  id:
    | '__root__'
    | '/(public)/(auth)'
    | '/(public)/_public'
    | '/api/auth/$'
    | '/(public)/_public/'
    | '/(public)/markets/'
    | '/(public)/(auth)/login/'
    | '/(public)/(auth)/onboarding/'
    | '/(public)/dashboard/home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicauthRouteRoute: typeof publicauthRouteRouteWithChildren
  publicPublicRouteRoute: typeof publicPublicRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  publicMarketsIndexRoute: typeof publicMarketsIndexRoute
  publicDashboardHomeIndexRoute: typeof publicDashboardHomeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)/_public': {
      id: '/(public)/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicPublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/(auth)': {
      id: '/(public)/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicauthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/markets/': {
      id: '/(public)/markets/'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof publicMarketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/_public/': {
      id: '/(public)/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicPublicIndexRouteImport
      parentRoute: typeof publicPublicRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/dashboard/home/': {
      id: '/(public)/dashboard/home/'
      path: '/dashboard/home'
      fullPath: '/dashboard/home'
      preLoaderRoute: typeof publicDashboardHomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/(auth)/onboarding/': {
      id: '/(public)/(auth)/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof publicauthOnboardingIndexRouteImport
      parentRoute: typeof publicauthRouteRoute
    }
    '/(public)/(auth)/login/': {
      id: '/(public)/(auth)/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicauthLoginIndexRouteImport
      parentRoute: typeof publicauthRouteRoute
    }
  }
}

interface publicauthRouteRouteChildren {
  publicauthLoginIndexRoute: typeof publicauthLoginIndexRoute
  publicauthOnboardingIndexRoute: typeof publicauthOnboardingIndexRoute
}

const publicauthRouteRouteChildren: publicauthRouteRouteChildren = {
  publicauthLoginIndexRoute: publicauthLoginIndexRoute,
  publicauthOnboardingIndexRoute: publicauthOnboardingIndexRoute,
}

const publicauthRouteRouteWithChildren = publicauthRouteRoute._addFileChildren(
  publicauthRouteRouteChildren,
)

interface publicPublicRouteRouteChildren {
  publicPublicIndexRoute: typeof publicPublicIndexRoute
}

const publicPublicRouteRouteChildren: publicPublicRouteRouteChildren = {
  publicPublicIndexRoute: publicPublicIndexRoute,
}

const publicPublicRouteRouteWithChildren =
  publicPublicRouteRoute._addFileChildren(publicPublicRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  publicauthRouteRoute: publicauthRouteRouteWithChildren,
  publicPublicRouteRoute: publicPublicRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  publicMarketsIndexRoute: publicMarketsIndexRoute,
  publicDashboardHomeIndexRoute: publicDashboardHomeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
