// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { SmartAccount$Type } from "./SmartAccount";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SmartAccount"]: SmartAccount$Type;
    ["contracts/proxy/SmartAccount.sol:SmartAccount"]: SmartAccount$Type;
  }

  interface ContractTypesMap {
    ["SmartAccount"]: GetContractReturnType<SmartAccount$Type["abi"]>;
    ["contracts/proxy/SmartAccount.sol:SmartAccount"]: GetContractReturnType<SmartAccount$Type["abi"]>;
  }
}
