// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    OptimisticOracleV3Interface: never;
  }

  interface ContractTypesMap {
    OptimisticOracleV3Interface: never;
  }
}
